const swaggerAutogen = require('swagger-autogen')()


const doc = {
    info: {
        version: "1.0.0",
        title: "Product API's",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json', "application/xml"],
    produces: ['application/json', "application/xml"],
    tags: [
        {
            "name": "Sample",
            "description": "Sample Endpoints"
        },
        {
            "name": "Products",
            "description": "Endpoints"
        }
    ]
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./src/routes/*.js'] // routes file have all api-routing 

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app')           // project's root file
})